# Exceções: continuação
#
# Veja o código no editor. O que acontecerá quando o executar? Verifique.
#
# Verá a seguinte mensagem em resposta:
# Traceback (most recent call last):
# File "lst.py", line 2, in 
# x = list[0]
# IndexError: list index out of range
#
# output
#
# Este é o IndexError.

my_list = []
x = my_list[0]